# yaml 配置
version: "3"
services:
  mysql:
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: "1362061587"
      MYSQL_USER: "root"
      MYSQL_PASS: "1362061587"
    image: "mysql:5.5"
    restart: always
    ports:
      - "3306:3306"
    volumes:
        - "./db:/var/lib/mysql"
        - "./conf/my.cnf:/etc/my.cnf"
  web:
    image: .
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql